# Generated by Django 5.1.5 on 2025-01-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0003_order_active_alter_contact_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='order_product',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order_product',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
