# Generated by Django 5.1.5 on 2025-01-15 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0004_rename_product_id_image_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?58?\\d{11,15}$')]),
        ),
    ]
