# Generated by Django 5.1.5 on 2025-01-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dimpro", "0006_rename_is_active_user_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user_email",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="order_product",
            old_name="price",
            new_name="dprice",
        ),
        migrations.AddField(
            model_name="alegrauser",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
