# Generated by Django 5.1.5 on 2025-01-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0007_rename_user_email_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_operator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
