# Generated by Django 5.1.5 on 2025-01-29 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0008_remove_user_is_operator_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
