# Generated by Django 5.1.5 on 2025-01-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dimpro", "0009_remove_user_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="group_objects",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
