# Generated by Django 5.1.5 on 2025-01-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dimpro", "0010_user_group_objects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="group_objects",
        ),
    ]
