# Generated by Django 5.1.5 on 2025-01-31 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0011_remove_user_group_objects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alegrauser',
            name='active',
        ),
    ]
