# Generated by Django 5.1.5 on 2025-01-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0012_remove_alegrauser_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='alegrauser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
