# Generated by Django 5.1.5 on 2025-02-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0013_alegrauser_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receivable',
        ),
    ]
