# Generated by Django 5.1.5 on 2025-02-05 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0014_delete_receivable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('rate', models.FloatField()),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exchange_rates_from_currency', to='dimpro.exchangecurrency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exchange_rates_to_currency', to='dimpro.exchangecurrency')),
            ],
        ),
    ]
