# Generated by Django 5.1.5 on 2025-02-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0018_pricetype_alter_order_total_alter_order_pricetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_product',
            old_name='dprice',
            new_name='price',
        ),
        migrations.AddField(
            model_name='order_product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
