# Generated by Django 5.1.5 on 2025-02-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dimpro", "0019_rename_dprice_order_product_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricetype",
            name="default",
        ),
    ]
