# Generated by Django 5.1.5 on 2025-02-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0020_remove_pricetype_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
