# Generated by Django 5.1.5 on 2025-02-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0021_alter_order_product_cost_alter_order_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
