# Generated by Django 5.1.5 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0022_alter_order_product_cost_alter_order_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
