# Generated by Django 5.1.5 on 2025-05-09 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0023_alter_order_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PricetypeTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('pricetype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='taxes', to='dimpro.pricetype')),
            ],
        ),
    ]
