# Generated by Django 5.1.5 on 2025-05-09 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0024_note_active_pricetypetax'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricetypeTax',
        ),
    ]
