# Generated by Django 5.1.5 on 2025-05-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0025_delete_pricetypetax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='active',
        ),
    ]
