# Generated by Django 5.1.5 on 2025-05-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0027_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
