# Generated by Django 5.1.5 on 2025-05-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0028_delete_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
