# Generated by Django 5.1.5 on 2025-05-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0029_alter_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
