# Generated by Django 5.1.5 on 2025-05-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0030_note_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
