# Generated by Django 5.1.5 on 2025-05-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0031_delete_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_staff_user', 'Can view staff user'), ('change_staff_user', 'Can change staff user'), ('delete_staff_user', 'Can delete staff user'), ('add_staff_user', 'Can add staff user')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
