# Generated by Django 5.1.5 on 2025-05-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0032_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('view_updatedb', 'Can update database')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_staff_user', 'Can view staff user'), ('change_staff_user', 'Can change staff user'), ('delete_staff_user', 'Can delete staff user'), ('add_staff_user', 'Can add staff user'), ('view_settings_user', 'Can view settings')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
