# Generated by Django 5.1.5 on 2025-05-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0033_alter_product_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('view_updatedb_product', 'Can update database')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
