# Generated by Django 5.1.5 on 2025-05-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0034_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('view_own_order', 'Can view its own order')], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
