# Generated by Django 5.1.5 on 2025-05-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0035_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_staff_user', 'Can view staff user'), ('change_staff_user', 'Can change staff user'), ('delete_staff_user', 'Can delete staff user'), ('add_staff_user', 'Can add staff user'), ('view_settings_user', 'Can view settings'), ('view_advanced_homepage_user', 'Can view advanced homepage')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
