# Generated by Django 5.1.5 on 2025-05-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0036_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('view_own_order', 'Can view its own order'), ('change_status_order', 'Can change order status'), ('view_export_order', 'Can export order')], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
