# Generated by Django 5.1.5 on 2025-07-15 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0037_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='from_currency',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='to_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='exchange_rate',
        ),
        migrations.DeleteModel(
            name='ExchangeCurrency',
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
