# Generated by Django 5.1.5 on 2025-07-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0038_remove_exchangerate_from_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('seller_name', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_staff_user', 'Can view staff user'), ('change_staff_user', 'Can change staff user'), ('delete_staff_user', 'Can delete staff user'), ('add_staff_user', 'Can add staff user'), ('view_settings_user', 'Can view settings'), ('view_advanced_homepage_user', 'Can view advanced homepage'), ('change_own_email_user', 'Can change its own email'), ('change_own_name_user', 'Can change its own name'), ('change_own_phonenumber_user', 'Can change its own phonenumber'), ('change_own_cardid_user', 'Can change its own card id'), ('change_own_address_user', 'Can change its own address')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='card_id',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
