# Generated by Django 5.1.5 on 2025-08-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0042_alegraseller_contactaddrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alegraseller',
            name='identification',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
