# Generated by Django 5.1.5 on 2025-08-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0043_alter_alegraseller_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactaddrequest',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=16),
        ),
    ]
