# Generated by Django 5.1.5 on 2025-08-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimpro', '0044_contactaddrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactaddrequest',
            name='seller',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
